const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true,
  outputDir: 'dist/app/salmi/',
  publicPath: '/app/salmi/', // (1) https://medium.com/js-dojo/how-to-solve-vue-js-prod-build-assets-relative-path-problem-71f91138dd79
  pwa: {
    manifestOptions: {
      version: '0.1',
      orientation: 'any',
      // screenshots : [
      //   {
      //     "src": "screenshot1.webp",
      //     "sizes": "1280x720",
      //     "type": "image/webp",
      //     "platform": "wide",
      //     "label": "Homescreen of Awesome App"
      //   },
      //   {
      //     "src": "screenshot2.webp",
      //     "sizes": "1280x720",
      //     "type": "image/webp",
      //     "platform": "wide",
      //     "label": "List of Awesome Resources available in Awesome App"
      //   }
      // ],
      // shortcuts : [
      //   {
      //     "name": "Today's agenda",
      //     "url": "/today",
      //     "description": "List of events planned for today"
      //   },
      //   {
      //     "name": "New event",
      //     "url": "/create/event"
      //   },
      //   {
      //     "name": "New reminder",
      //     "url": "/create/reminder"
      //   }
      // ]
    }
  },
  pluginOptions: {
    sitemap: {
      urls: [
        'https://castenettoa.com/app/salmi/',
        'https://castenettoa.com/app/salmi/penitenziali',
        'https://castenettoa.com/app/salmi/blog/libro-dei-salmi',
        'https://castenettoa.com/app/salmi/words', // parole + frequenti nei salmi
        'https://castenettoa.com/app/salmi/favorites',
        'https://castenettoa.com/app/salmi/parole-di-luce',

        'https://castenettoa.com/app/salmi/b/1',
        'https://castenettoa.com/app/salmi/b/2',
        'https://castenettoa.com/app/salmi/b/3',
        'https://castenettoa.com/app/salmi/b/4',
        'https://castenettoa.com/app/salmi/b/5',

        'https://castenettoa.com/app/salmi/s/1',
        'https://castenettoa.com/app/salmi/s/2',
        'https://castenettoa.com/app/salmi/s/3',
        'https://castenettoa.com/app/salmi/s/4',
        'https://castenettoa.com/app/salmi/s/5',
        'https://castenettoa.com/app/salmi/s/6',
        'https://castenettoa.com/app/salmi/s/7',
        'https://castenettoa.com/app/salmi/s/8',
        'https://castenettoa.com/app/salmi/s/9',
        'https://castenettoa.com/app/salmi/s/10',
        'https://castenettoa.com/app/salmi/s/11',
        'https://castenettoa.com/app/salmi/s/12',
        'https://castenettoa.com/app/salmi/s/13',
        'https://castenettoa.com/app/salmi/s/14',
        'https://castenettoa.com/app/salmi/s/15',
        'https://castenettoa.com/app/salmi/s/16',
        'https://castenettoa.com/app/salmi/s/17',
        'https://castenettoa.com/app/salmi/s/18',
        'https://castenettoa.com/app/salmi/s/19',
        'https://castenettoa.com/app/salmi/s/20',
        'https://castenettoa.com/app/salmi/s/21',
        'https://castenettoa.com/app/salmi/s/22',
        'https://castenettoa.com/app/salmi/s/23',
        'https://castenettoa.com/app/salmi/s/24',
        'https://castenettoa.com/app/salmi/s/25',
        'https://castenettoa.com/app/salmi/s/26',
        'https://castenettoa.com/app/salmi/s/27',
        'https://castenettoa.com/app/salmi/s/28',
        'https://castenettoa.com/app/salmi/s/29',
        'https://castenettoa.com/app/salmi/s/30',
        'https://castenettoa.com/app/salmi/s/31',
        'https://castenettoa.com/app/salmi/s/32',
        'https://castenettoa.com/app/salmi/s/33',
        'https://castenettoa.com/app/salmi/s/34',
        'https://castenettoa.com/app/salmi/s/35',
        'https://castenettoa.com/app/salmi/s/36',
        'https://castenettoa.com/app/salmi/s/37',
        'https://castenettoa.com/app/salmi/s/38',
        'https://castenettoa.com/app/salmi/s/39',
        'https://castenettoa.com/app/salmi/s/40',
        'https://castenettoa.com/app/salmi/s/41',
        'https://castenettoa.com/app/salmi/s/42',
        'https://castenettoa.com/app/salmi/s/43',
        'https://castenettoa.com/app/salmi/s/44',
        'https://castenettoa.com/app/salmi/s/45',
        'https://castenettoa.com/app/salmi/s/46',
        'https://castenettoa.com/app/salmi/s/47',
        'https://castenettoa.com/app/salmi/s/48',
        'https://castenettoa.com/app/salmi/s/49',
        'https://castenettoa.com/app/salmi/s/50',
        'https://castenettoa.com/app/salmi/s/51',
        'https://castenettoa.com/app/salmi/s/52',
        'https://castenettoa.com/app/salmi/s/53',
        'https://castenettoa.com/app/salmi/s/54',
        'https://castenettoa.com/app/salmi/s/55',
        'https://castenettoa.com/app/salmi/s/56',
        'https://castenettoa.com/app/salmi/s/57',
        'https://castenettoa.com/app/salmi/s/58',
        'https://castenettoa.com/app/salmi/s/59',
        'https://castenettoa.com/app/salmi/s/60',
        'https://castenettoa.com/app/salmi/s/61',
        'https://castenettoa.com/app/salmi/s/62',
        'https://castenettoa.com/app/salmi/s/63',
        'https://castenettoa.com/app/salmi/s/64',
        'https://castenettoa.com/app/salmi/s/65',
        'https://castenettoa.com/app/salmi/s/66',
        'https://castenettoa.com/app/salmi/s/67',
        'https://castenettoa.com/app/salmi/s/68',
        'https://castenettoa.com/app/salmi/s/69',
        'https://castenettoa.com/app/salmi/s/70',
        'https://castenettoa.com/app/salmi/s/71',
        'https://castenettoa.com/app/salmi/s/72',
        'https://castenettoa.com/app/salmi/s/73',
        'https://castenettoa.com/app/salmi/s/74',
        'https://castenettoa.com/app/salmi/s/75',
        'https://castenettoa.com/app/salmi/s/76',
        'https://castenettoa.com/app/salmi/s/77',
        'https://castenettoa.com/app/salmi/s/78',
        'https://castenettoa.com/app/salmi/s/79',
        'https://castenettoa.com/app/salmi/s/80',
        'https://castenettoa.com/app/salmi/s/81',
        'https://castenettoa.com/app/salmi/s/82',
        'https://castenettoa.com/app/salmi/s/83',
        'https://castenettoa.com/app/salmi/s/84',
        'https://castenettoa.com/app/salmi/s/85',
        'https://castenettoa.com/app/salmi/s/86',
        'https://castenettoa.com/app/salmi/s/87',
        'https://castenettoa.com/app/salmi/s/88',
        'https://castenettoa.com/app/salmi/s/89',
        'https://castenettoa.com/app/salmi/s/90',
        'https://castenettoa.com/app/salmi/s/91',
        'https://castenettoa.com/app/salmi/s/92',
        'https://castenettoa.com/app/salmi/s/93',
        'https://castenettoa.com/app/salmi/s/94',
        'https://castenettoa.com/app/salmi/s/95',
        'https://castenettoa.com/app/salmi/s/96',
        'https://castenettoa.com/app/salmi/s/97',
        'https://castenettoa.com/app/salmi/s/98',
        'https://castenettoa.com/app/salmi/s/99',
        'https://castenettoa.com/app/salmi/s/100',
        'https://castenettoa.com/app/salmi/s/101',
        'https://castenettoa.com/app/salmi/s/102',
        'https://castenettoa.com/app/salmi/s/103',
        'https://castenettoa.com/app/salmi/s/104',
        'https://castenettoa.com/app/salmi/s/105',
        'https://castenettoa.com/app/salmi/s/106',
        'https://castenettoa.com/app/salmi/s/107',
        'https://castenettoa.com/app/salmi/s/108',
        'https://castenettoa.com/app/salmi/s/109',
        'https://castenettoa.com/app/salmi/s/110',
        'https://castenettoa.com/app/salmi/s/111',
        'https://castenettoa.com/app/salmi/s/112',
        'https://castenettoa.com/app/salmi/s/113',
        'https://castenettoa.com/app/salmi/s/114',
        'https://castenettoa.com/app/salmi/s/115',
        'https://castenettoa.com/app/salmi/s/116',
        'https://castenettoa.com/app/salmi/s/117',
        'https://castenettoa.com/app/salmi/s/118',
        'https://castenettoa.com/app/salmi/s/119',
        'https://castenettoa.com/app/salmi/s/120',
        'https://castenettoa.com/app/salmi/s/121',
        'https://castenettoa.com/app/salmi/s/122',
        'https://castenettoa.com/app/salmi/s/123',
        'https://castenettoa.com/app/salmi/s/124',
        'https://castenettoa.com/app/salmi/s/125',
        'https://castenettoa.com/app/salmi/s/126',
        'https://castenettoa.com/app/salmi/s/127',
        'https://castenettoa.com/app/salmi/s/128',
        'https://castenettoa.com/app/salmi/s/129',
        'https://castenettoa.com/app/salmi/s/130',
        'https://castenettoa.com/app/salmi/s/131',
        'https://castenettoa.com/app/salmi/s/132',
        'https://castenettoa.com/app/salmi/s/133',
        'https://castenettoa.com/app/salmi/s/134',
        'https://castenettoa.com/app/salmi/s/135',
        'https://castenettoa.com/app/salmi/s/136',
        'https://castenettoa.com/app/salmi/s/137',
        'https://castenettoa.com/app/salmi/s/138',
        'https://castenettoa.com/app/salmi/s/139',
        'https://castenettoa.com/app/salmi/s/140',
        'https://castenettoa.com/app/salmi/s/141',
        'https://castenettoa.com/app/salmi/s/142',
        'https://castenettoa.com/app/salmi/s/143',
        'https://castenettoa.com/app/salmi/s/144',
        'https://castenettoa.com/app/salmi/s/145',
        'https://castenettoa.com/app/salmi/s/146',
        'https://castenettoa.com/app/salmi/s/147',
        'https://castenettoa.com/app/salmi/s/148',
        'https://castenettoa.com/app/salmi/s/149',
        'https://castenettoa.com/app/salmi/s/150',
      ]
    }
  }
})

// vue.config.js

module.exports = {
  pluginOptions: {
    sitemap: {
      urls: [
        'https://example.com/',
        'https://example.com/about',
      ]
    }
  }
}